### PR TITLE
Handle rawRequest errors

### PR DESCRIPTION
**Pull request by redDwarf03**
This PR contains a new feature to manage error from EVM Wallet
This allows to add specific Exception to manage the behaviour when user rejects the request in the wallet.
The other thing is to manage RPC Error. This useful to manage Revert process in solidity smart contrat and get the `error` 

`EthereumUserRejected` = When user rejects manually in the wallet a transaction
`RPCError` = If error is a RPC Error and contains `code`, `message` and `data` fields
`EthereumException` = If error is not from a RPC Error and contains `code`, `message` and `data` fields
`EthersException` = If error is not from a RPC Error and contains `code`, `reason` fields
`UnimplementedError`= if error is not implemented

In the case of RPCError, client can manage json content
An example:
```
{
  "value": {
    "code": -32603,
    "data": {
      "message": "VM Exception while processing transaction: revert ERC20: transfer amount exceeds balance",
      "code": -32000,
      "data": {
        "0x5c67ee0be489da9e85c5380b63120a10cef370622b282f3f623b80355461327e": {
          "error": "revert",
          "program_counter": 2411,
          "return": "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002645524332303a207472616e7366657220616d6f756e7420657863656564732062616c616e63650000000000000000000000000000000000000000000000000000",
          "reason": "ERC20: transfer amount exceeds balance"
        },
        "stack": "RuntimeError: VM Exception while processing transaction: revert ERC20: transfer amount exceeds balance\n    at Function.RuntimeError.fromResults (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/utils/runtimeerror.js:94:13)\n    at BlockchainDouble.processBlock (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/blockchain_double.js:627:24)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
        "name": "RuntimeError"
      }
    }
  }
}
```

The `reason` field contains the revert message.

### CODE REVIEW

**Comment by redDwarf03** [comment]
I don't know why, but i met some issue with `dartify`method....
No issue with webthree compilation... but when i used it with my flutter web Dapps, sometimes i have this message when i want to build for example my freezed classes  :

Any idea ?

```
flutter packages pub run build_runner build --delete-conflicting-outputs
Deprecated. Use `dart run` instead.
[INFO] Generating build script completed, took 195ms
[WARNING] ../../../flutter/.pub-cache/git/webthree-76115fced4e4f950c7418c74d36af46192525679/lib/src/core/exception.dart:47:43: Error: Method not found: 'dartify'.
      final err = json.decode(json.encode(dartify(e))) as Map<String, dynamic>;
                                          ^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dev/js-0.6.7/lib/js_util.dart:8:1: Error: Dart library 'dart:js_util' is not available on this platform.
export 'dart:js_util';
^
Context: The unavailable library 'dart:js_util' is imported through these packages:

    build.dart => package:webthree => package:js => dart:js_util

Detailed import paths for (some of) the these imports:

    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/contracts.dart => package:webthree/src/contracts/abi/abi.dart => package:webthree/src/contracts/abi/arrays.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/contracts.dart => package:webthree/src/contracts/abi/abi.dart => package:webthree/src/contracts/abi/arrays.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/wallet.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/contracts.dart => package:webthree/src/contracts/abi/arrays.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/contracts.dart => package:webthree/src/contracts/abi/arrays.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/wallet.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/contracts.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/contracts.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/wallet.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/contracts.dart => package:webthree/src/contracts/deployed_contract.dart => package:webthree/src/contracts/abi/abi.dart => package:webthree/src/contracts/abi/arrays.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/contracts.dart => package:webthree/src/contracts/deployed_contract.dart => package:webthree/src/contracts/abi/abi.dart => package:webthree/src/contracts/abi/arrays.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/wallet.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/contracts.dart => package:webthree/src/contracts/generated_contract.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/src/builder/documentation.dart => package:webthree/contracts.dart => package:webthree/src/contracts/abi/abi.dart => package:webthree/src/contracts/abi/arrays.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/src/builder/documentation.dart => package:webthree/contracts.dart => package:webthree/src/contracts/abi/abi.dart => package:webthree/src/contracts/abi/arrays.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/wallet.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/src/builder/documentation.dart => package:webthree/contracts.dart => package:webthree/src/contracts/abi/arrays.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/src/builder/documentation.dart => package:webthree/contracts.dart => package:webthree/src/contracts/abi/arrays.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/wallet.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/src/builder/documentation.dart => package:webthree/contracts.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/src/builder/documentation.dart => package:webthree/contracts.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/wallet.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/src/builder/documentation.dart => package:webthree/contracts.dart => package:webthree/src/contracts/deployed_contract.dart => package:webthree/src/contracts/abi/abi.dart => package:webthree/src/contracts/abi/arrays.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/src/builder/documentation.dart => package:webthree/contracts.dart => package:webthree/src/contracts/deployed_contract.dart => package:webthree/src/contracts/abi/abi.dart => package:webthree/src/contracts/abi/arrays.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/wallet.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/src/builder/documentation.dart => package:webthree/contracts.dart => package:webthree/src/contracts/generated_contract.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/src/builder/utils.dart => package:webthree/contracts.dart => package:webthree/src/contracts/abi/abi.dart => package:webthree/src/contracts/abi/arrays.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/src/builder/utils.dart => package:webthree/contracts.dart => package:webthree/src/contracts/abi/abi.dart => package:webthree/src/contracts/abi/arrays.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/wallet.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    build.dart => package:webthree/src/builder/builders.dart => package:webthree/src/builder/generator.dart => package:webthree/src/builder/utils.dart => package:webthree/contracts.dart => package:webthree/src/contracts/abi/arrays.dart => package:webthree/src/contracts/abi/integers.dart => package:webthree/credentials.dart => package:webthree/src/credentials/credentials.dart => package:webthree/webthree.dart => package:webthree/src/core/exception.dart => package:js/js_util.dart => dart:js_util
    ...

[INFO] Precompiling build script... completed, took 741ms
[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

**Comment by makinghappen** [comment]
@redDwarf03 if this error comes from the platform not having a browser, I think a conditional import should be used, like in this example https://github.com/devopsdao/webthree/blob/master/example/metamask/web/main.dart#L6
`import 'package:js/js.dart'
    if (dart.library.io) 'package:webthree/lib/src/browser/js-stub.dart'
    if (dart.library.js) 'package:js/js.dart';
import 'package:webthree/browser.dart'
    if (dart.library.io) 'package:webthree/lib/src/browser/dart_wrappers_stub.dart'
    if (dart.library.js) 'package:webthree/browser.dart';`

**Comment by redDwarf03** [comment]
> @redDwarf03 if this error comes from the platform not having a browser, I think a conditional import should be used, like in this example https://github.com/devopsdao/webthree/blob/master/example/metamask/web/main.dart#L6
> 
> ```
> import 'package:js/js.dart'
>     if (dart.library.io) 'package:webthree/lib/src/browser/js-stub.dart'
>     if (dart.library.js) 'package:js/js.dart';
> import 'package:webthree/browser.dart'
>     if (dart.library.io) 'package:webthree/lib/src/browser/dart_wrappers_stub.dart'
>     if (dart.library.js) 'package:webthree/browser.dart';
> ```

it seems working with `import 'package:webthree/src/browser/js_util_stub.dart';``
but i don't which lib use for dart.library.io and i don't understand why it's necessary to use dart.io because dart_wrappers is in src/browser folder... 

Sorry. this point is not clear for me

**Comment by redDwarf03** [comment]
i'm trying something different. i'm finishing to test and tell you

**Comment by redDwarf03** [comment]
hello. i try to finish today my tests

**Comment by makinghappen** [comment]
hi @redDwarf03 been merging this PR, please let me know when its ready and I will publish a new build

**Comment by redDwarf03** [comment]
For me, tests are ok.
In DApp, to manage RPC error, it's possible to do that:

1) Catch error from sendTransaction method
```
Future<String> sendTransactionWithErrorManagement(
    Web3Client web3Client,
    CredentialsWithKnownAddress credentials,
    Transaction transaction,
    int chainId,
  ) async {
    try {
      return await web3Client.sendTransaction(
        credentials,
        transaction,
        chainId: chainId,
      );
    } catch (e) {
      if (e is EthereumUserRejected) {
        throw const Failure.userRejected();
      }
      if (e is EthereumException) {
        throw Failure.other(cause: e.data, stack: e.message);
      }
      if (e is EthersException) {
        throw Failure.other(cause: e.rawError, stack: e.reason);
      }
      if (e is RPCError) {
        const encoder = JsonEncoder.withIndent('  ');
        final validJson = encoder.convert(e.data);
        final Map<String, dynamic> jsonMap = json.decode(validJson);
        final rpcErrorEVMData =
            RPCErrorEVMData.fromJson(jsonMap.entries.first.value);
        throw Failure.rpcErrorEVM(data: {'Some_Key': rpcErrorEVMData});
      }
      throw Failure.other(cause: e.toString());
    }
  }
```

2) Create classes to manage these errors
```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'failures.freezed.dart';
part 'failures.g.dart';

class FailureJsonConverter
    extends JsonConverter<Failure, Map<String, dynamic>> {
  const FailureJsonConverter();

  @override
  Failure fromJson(Map<String, dynamic> json) {
    return Failure.fromJson(json);
  }

  @override
  Map<String, dynamic> toJson(Failure object) => object.toJson();
}

@freezed
class Failure with _$Failure implements Exception {
  const Failure._();
  const factory Failure.userRejected() = UserRejected;
  const factory Failure.connectivityEVM() = ConnectivityEVM;
  const factory Failure.rpcErrorEVM({
    Map<String, RPCErrorEVMData>? data,
    String? stack,
    String? name,
  }) = RPCErrorEVM;

  const factory Failure.other({
    Object? cause,
    String? stack,
  }) = OtherFailure;

  factory Failure.fromJson(Map<String, dynamic> json) =>
      _$FailureFromJson(json);
}

@freezed
class RPCErrorEVMData with _$RPCErrorEVMData {
  const factory RPCErrorEVMData({
    required String error,
    // ignore: non_constant_identifier_names
    required int program_counter,
    // ignore: invalid_annotation_target
    @JsonKey(name: 'return') required String returnValue,
    required String reason,
  }) = _RPCErrorEVMData;

  factory RPCErrorEVMData.fromJson(Map<String, dynamic> json) =>
      _$RPCErrorEVMDataFromJson(json);
}
```  

3) Display revert's reason:
```
    if (failure is RPCErrorEVM) {
      return (failure! as RPCErrorEVM).data!['Some_Key']!.reason;
    }
```

**Pull request merged**
